# Generated by Django 4.2.5 on 2023-10-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blog_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-timeStamp']},
        ),
    ]
